#!/usr/bin/env python

import rospy
import os, glob
import csv
import rospkg

from std_msgs.msg import Float32MultiArray
from geometry_msgs.msg import Point


rospack = rospkg.RosPack()

# def sauce_callback(input):




if __name__=="__main__":
    rospy.init_node('sauce_cmd')
    sauce_input = [1,15,4]
    sauce_pos = open(os.path.join(rospack.get_path("vrep_creative_description"), "position", "init_pos.csv"), 'r')
    reader = csv.reader(sauce_pos)
    lines = list(reader)
    group_pub = rospy.Publisher('group_pos',Point,queue_size=1)
    group_num = rospy.Publisher('group_num',Float32MultiArray,queue_size=1)
    group_pos = Point()
    group_pos.x = float(lines[0][3*sauce_input[0]-3])
    group_pos.y = float(lines[0][3*sauce_input[0]-2])
    group_pos.z = float(lines[0][3*sauce_input[0]-1])
    print("Sauce #: ", sauce_input[0])
    print("Sauce Weight (g): ", sauce_input[1])
    print("Burner #: ", sauce_input[2])
    while not rospy.is_shutdown():
        group_pub.publish(group_pos) 
        group_num_list = Float32MultiArray(data=sauce_input)
        group_num.publish(group_num_list)
    # rospy.spin()